name: Publish to Github releases

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: npm install
        run: |
          npm install
      - name: Install VSCE
        run: |
          sudo npm install -g vsce
      - name: Publish
        run: |
          vsce package
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.vsix"
